#!/usr/bin/env bash

set -eo pipefail

dependencies=$(jq -r ".dependencies | keys[]" "$1")
test -n "$dependencies" && pnpm add $dependencies
dev_dependencies=$(jq -r ".devDependencies | keys[]" "$1")
test -n "$dev_dependencies" && pnpm add -D $dev_dependencies
