# Generated by Django 4.2.3 on 2023-08-04 20:19

from django.db import migrations, models
import furryminder2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Billy', max_length=250)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('health', models.IntegerField(default=150)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow')], default=furryminder2.models.random_color, max_length=1)),
                ('accessory', models.SmallIntegerField(blank=True, choices=[(0, 'Bow'), (1, 'Hat')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('due', models.DateTimeField()),
                ('repeat', models.CharField(max_length=250)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
