# Generated by Django 4.2.3 on 2023-08-08 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import furryminder2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('due', models.DateTimeField()),
                ('repeat', models.CharField(max_length=250)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Billy', max_length=250)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('health', models.IntegerField(default=150)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow')], default=furryminder2.models.random_color, max_length=1)),
                ('accessory', models.SmallIntegerField(blank=True, choices=[(0, 'Bow'), (1, 'Hat')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
